### ISSUE TITLE
Need an instance for cdma.fifo file

### ISSUE THREAD

**Issue by siavashaaa32002** [anastas/gr-cdma#19]
Dear all,
I am using the gr-cdma blocks. For running the gnuradio file of cdma_rx.grc, one need 2 usrp to make the cdma.fifo file, but I have only one (N210). I would be pleased if someone can send me an example of cdma.fifo file for my tests?
best regards,
Siavash Ahmadi

**Comment by siavashaaa32002** [comment]
My email is: siavashaaa32002@yahoo.com

**Comment by anastas** [comment]
Hi Siavash,

as mentioned in the README file, the cdma.fifo is not any specific file, but a "pipe" you create in your Linux so that the Tx sends data to the Rx. You can create it in your Linux environment by running the following command:

mkfifo /tmp/cdma.fifo

**Comment by siavashaaa32002** [comment]
Hi anastas,

Thank you very much. Though I tried to make fifo file by cdma_tx, it did not work and nothing added to the cdma.fifo made by mkfifo /tmp/cdma.fifo. However, I could use cdma_txrx as a good example of working with cdma. My goal is receiving the w-cdma packets (i mean 3g in frequnecy bands of 900 or 2120-2170) using USRP N210 and gnuradio/python/cc programming. Can you please help or guide me, how I can do this by using your cdma blocks? or maybe I should do from beginning? Is there any clear guidance or source for this?

Bests,

**Comment by anastas** [comment]
I do not understand your statement:
"Though I tried to make fifo file by cdma_tx, it did not work and nothing added to the cdma.fifo made by mkfifo /tmp/cdma.fifo"

There is nothing for you to see in that file!
It is used internally by Linux to pass information from the Tx to the Rx, so that the two processes
cdma_tx and cdma_rx communicate with each other...

**Comment by siavashaaa32002** [comment]
Aha,
I understood what you mean about "Pipe" now!! It is because I am an electrical engineer and not computer science :D. Sorry, and thanks a lot. 
But how about WCDMA in my last comment?
Again thanks for your answers.
