### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by JarekGit55** [anastas/gr-cdma#21]
[ 29%] Built target gnuradio-cdma
[ 38%] Built target test-cdma
[ 45%] Built target _cdma_swig_doc_tag
[ 48%] Generating doxygen xml for cdma_swig_doc docs
/bin/sh: 1: cdma_swig_doc_swig_docs/Doxyfile: Permission denied
swig/CMakeFiles/cdma_swig_swig_doc.dir/build.make:64: recipe for target 'swig/cdma_swig_doc_swig_docs/xml/index.xml' failed
make[2]: *** [swig/cdma_swig_doc_swig_docs/xml/index.xml] Error 126
CMakeFiles/Makefile2:312: recipe for target 'swig/CMakeFiles/cdma_swig_swig_doc.dir/all' failed
make[1]: *** [swig/CMakeFiles/cdma_swig_swig_doc.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

I did it twice following README.md with the same result. What is wrong ?

**Comment by anastas** [comment]
There has been a similar question on discuss-gnuradio this March.
There seems to be a Doxygen problem.
You can build it without Doxygen support.

see here if this fixes your problem:

https://lists.gnu.org/archive/html/discuss-gnuradio/2017-03/msg00313.html

**Comment by liuhp** [comment]
@JarekGit55 
Hi, did you solve your problem? 
I have the same problem as yours, could you tell me how to solve it?
I'm looking forward to your reply!
    liuhp

**Comment by anastas** [comment]
have you tried the above solution?

**Comment by V18006** [comment]
I am having same error. Sirs, I am using GNU make
How to correct it? I have cloned as suggested by Marcus, but still error persists!!

**Comment by anastas** [comment]
What exactly did you do with the above mentioned solution?

Have you tried to build it without documentation?
cmake -DENABLE_DOXYGEN=OFF "PATH TO YOUR gr-cdma TRUNK"
Does this work?

**Comment by V18006** [comment]
Sir,
I used just as you said and it worked. I used 
cmake -DENABLE_DOXYGEN=OFF "PATH TO YOUR gr-cdma TRUNK"
Thank you
