### ISSUE TITLE
My question is about modulation 

### ISSUE THREAD

**Issue by lbb123** [anastas/gr-cdma#23]
As I kown,the CDMA system use multi-carrier modulation but I didn't see multifrequency  carrier?it that in usrp?

**Comment by anastas** [comment]
CDMA has nothing to do with multi-carrier!
They are two different transmission schemes.
You can use multi-carrier in CDMA but this is not a component of CDMA.

**Comment by lbb123** [comment]
In your mean,CDMA just process the baseband signal?What difference about the MC-CDMA,CDMA2000 in 3G and this system?

**Comment by anastas** [comment]
This is not a good place for you to learn what CDMA is.
If you want to get an idea start here:
https://en.wikipedia.org/wiki/Code-division_multiple_access

All my code is open source and sufficiently documented.
If you want to see what I am doing all you have to do is read it!
Let me know if you have any questions on my project.

**Comment by lbb123** [comment]
Thank you very much~,anastas
