### ISSUE TITLE
Getting started with gr-cdma

### ISSUE THREAD

**Issue by superzaki** [anastas/gr-cdma#27]
Hi Anastas et al
First, let me thank you for your huge efforts and contributions to this project..
I'm a PhD student studying amateur radios for space applications. I tried to run you CDMA example on Ubuntu 16.04 and I'm failing miserably. Your project worked flawlessly on Windows tho
I followed the detailed installation instructions but the main issue I'm getting is:
 Param - Import(import):
	Import "import cdma" failed.
and 
import cdma.cdma_parameters as cp

if someone can help me with this, I'll be eternally grateful 
ps. I followed the conversations from 3 years ago but none of the solutions actually worked

**Comment by anastas** [comment]
please post all the DETAILED steps you followed, together with intermediate tests that succeeded/failed on discuss-gnuradio list.
I will not respond to any requests on github.

**Comment by superzaki** [comment]
Thank you
