### ISSUE TITLE
unable to import cdma due to hard-coded prefix

### ISSUE THREAD

**Issue by charles1024** [anastas/gr-cdma#28]
The prefix for the gr-cdma directory is a hard-coded, absolute path on line 90 of cdma_parameters.py:

`prefix="/home/anastas/gr-cdma/"  # put the prefix of your gr-cdma trunk`

This results in a non-existent file when trellis.fsm() is called.

This should be added to the README or changed to use either a relative path or the  prefix configured by PyBOMBs.

**Comment by anastas** [comment]
The README file CLEARLY states:

"Edit the file gr-cdma/python/cdma_parameters.py and set the prefix variable with your gr-cdma trunk directory.
Note: this is your git directory prefix not the installation prefix!

prefix="YOUR_PREFIX_HERE/gr-cdma" # put the prefix of your gr-cdma trunk"
