### ISSUE TITLE
Using packet error calculator

### ISSUE THREAD

**Issue by abifedun** [anastas/gr-cdma#29]
Hi, I really appreciate this repository as it gave an intuitive insight into the working mechanism of a cdma system. However, I would like to use the packet error calculator developed in your system for OFDM example in GNURADIO. I have currently tried using the packet error calculator block by attaching it with stream tagged to pdu block. However, I couldn't get a message printed on the terminal for packet error loss. therefore, May I know what i might be doing wrong and how you could guide me on making this block work. thanks

**Comment by anastas** [comment]
Hi,

I think it is best if you ask this question to the discuss-gnuradio list.
I suggest you give an example of your grc graph and provide  a lot of details for your problem.
It is very difficult for people to guess what you are doing if you don't tell them...
