### ISSUE TITLE
Scrambling in cdma_tx_hier1.grc

### ISSUE THREAD

**Issue by superzaki** [anastas/gr-cdma#30]
Hi Achilleas 

I'm using your cdma project for quite some time now. Works great and lots of learning opportunities out of this project. Just a quick question:
at the output of cdma_tx_hier1, you're using a simple "add" operation instead of the "xor" required for scrambling. If I'm not wrong, you're using the long "training" sequence as a scrambling sequence, right? 

Many thanks,
Zak

**Comment by anastas** [comment]
Well, not quite:

You should think of this system as superposition (thus the add) of two orthogonal channels: the first is the data channel (which is a CDMA system itself with a spreading code the length of 1 data symbol) AND a synchronization channel (which is a CDMA system itself). The latter is transmitting a known training sequence (the length of a frame) that is spread (using its own spreading code, with period 1 symbol).
Both channels spread their symbols by means of a "code" with period 1 symbol.
Nowhere in this implementation will you see XOR operations etc: CDMA really means a system with BW much higher than the symbol rate.

**Comment by superzaki** [comment]
That clarifies a lot of questions I had then, many thanks for the explanation
So technically, the spreading codes are: "pulse_training" & "pulse_data" used as taps by the interp. FIR filters? 
If yes, does this mean that each CDMA channel is spread using interpolation rather than the classic unipolar xor or bipolar multip?

**Comment by anastas** [comment]
Yes.
Interpolating filter is essentially turning the sequence of data symbols to a sequence of spread chips:
eg: data = 1 1 -1 and pulse_data = 1 -1 1 -1 then the interpolation filter with factor 4 and taps puls_data
will create the chips: 1 -1 1 -1,  1 -1 1 -1, -1 1 -1 1

**Comment by superzaki** [comment]
Great!
If you don't mind me asking further questions unrelated to the Tx
At the Rx, are you using maximum likelihood technique for sequence detection by your bloc "freq_timing_estimator" and use the locally generated "training" sequence in "chopper_correlator" to align or correct the phase offset of the incoming sequence?

**Comment by anastas** [comment]
Well, I would prefer if you asked more specific questions.
Anyway, here is how synchronization works:
The Rx has to estimate frequency and timming.
For this it has a bank of n_filt parallel matched filters, each matched to the training sequence and each of them at a different frequency within the uncertainty range you want to explore.
The max of the abs(.) of the output of all these filters is send to a peak_detector in order to estimate timing and frequency offset.
The peak detectors creates a sequence of "flags" that point to the beginning of each frame.
The remaining part of the Rx chops this frame and does the rest of the tasks:
phase estimations, demodulation, decoding, etc.

**Comment by superzaki** [comment]
Very intersting indeed!
So the "freq_xlating_fft_filter_ccc(1, numpy.kron(seq1,seq2), self.freqs[i], 1)" acts as "n_filt" and is the configuration of the parallel rake fingers for each channel?

**Comment by superzaki** [comment]
@anastas 
Do you have a paper or any written work on gr-cdma? I want to cite it in my thesis
Thanks

**Comment by anastas** [comment]
> Very intersting indeed!
> So the "freq_xlating_fft_filter_ccc(1, numpy.kron(seq1,seq2), self.freqs[i], 1)" acts as "n_filt" and is the configuration of the parallel rake fingers for each channel?

Yes, this is ONE of the n_filt filters that is part of the filter bank.

> @anastas
> Do you have a paper or any written work on gr-cdma? I want to cite it in my thesis
> Thanks

I guess you can cite the project on github. BTW, there is extensive (but not polished) documentation on all these in the project.

**Comment by superzaki** [comment]
> Yes, this is ONE of the n_filt filters that is part of the filter bank.

Thanks for the quick reply

> I guess you can cite the project on github. BTW, there is extensive (but not polished) documentation on all these in the project.

I'll certainly do. Would you kindly direct me where I can find the documentation?

**Comment by anastas** [comment]
cmake -DENABLE_DOXYGEN=ON "PATH TO YOUR gr-cdma TRUNK"

this will compile all documentation available for each block

**Comment by superzaki** [comment]
Once again, thanks @anastas 
I'll close this issue as you've replied to all my questions
I will not stop myseft from posting other questions should I have any :)
