### ISSUE TITLE
CDMA multiple transmitters - one receiver, how to separate the sequences?

### ISSUE THREAD

**Issue by superzaki** [anastas/gr-cdma#31]
Hi Anastas

I'm wondering if it's possible to implement a scenario where a Rx receives CDMA packets from multiple Tx nodes. My questions are
1- How can the receiver distinguish between different users ? is it by using different sets of cp.pulse_training and cp.training?
2- How can I mix the sequences generated by each Tx in the channel ? can this be done by a simple addition?
I've attached a diagram explaining further what I plan to do.

Many thanks in advance,
Zak

![cmda question](https://user-images.githubusercontent.com/8672797/57690476-a251e400-7639-11e9-806c-4c618317177f.png)

**Comment by anastas** [comment]
You can use two Tx's with different pulses (both sync and data). Try to select them as orthogonal to each other as possible.

Then you have to duplicate the Rx's, one for  each  of the Tx's

**Comment by superzaki** [comment]
I see, 
I think I didn't use orthogonal pulses, I'll go with Walsh then.
Is it possible to use one common sync channel shared accorss all Tx's. In other words, keep the sync with its pulses and assign different Walsh pulses to the data channel?
Thanks

**Comment by anastas** [comment]
The sync channel is used to synchronize timing and frequency between Tx and Rx.
If you use one sync channel, how do you envision the sync to happen between each Tx and the Rx?

**Comment by superzaki** [comment]
If sync flags are generated based on cp.training x cp.pulse_training_t. I figured same sync channel can be used? 
It worked actually now by increasing training_filter_length while reducing training_percent. 
Will try different sync channels and see what it gives
