### ISSUE TITLE
Errors on running cdma_txrx.grc

### ISSUE THREAD

**Issue by shrin18** [anastas/gr-cdma#34]
Hello Anastas,

I am using GNU Radio Companion 3.7.13 on Ubuntu 18.04.
I have build the GNU Project by source and installed all dependencies separately and have successfully built the anastas/gr-cdma project as well.

As mentioned on the Repo I reloaded all the blocks 
"cdma_tx_hier.grc",

"chopper_correlator.grc",

"cdma_rx_hier.grc",

and Tried to load application cdma_txrx.grc. However it is giving the following errors:

CDMA PARAMETERS : for adaptive coded modulation
Traceback (most recent call last):
  File "/home/rslab/gr-cdma/apps/cdma_txrx.py", line 33, in <module>
    from gnuradio.wxgui import forms

  File "/usr/local/lib/python2.7/dist-packages/gnuradio/wxgui/forms/__init__.py", line 36, in <module>
    from forms import \

  File "/usr/local/lib/python2.7/dist-packages/gnuradio/wxgui/forms/forms.py", line 64, in <module>
    class _form_base(pubsub, wx.BoxSizer):

TypeError: Error when calling the metaclass bases
    multiple bases have instance lay-out conflict

Can you help on this matter.

**Comment by anastas** [comment]
probably some incompatibility issues with your wx installation.
You can always substitute all wx widgets with qt ones.

You can try the already provided qt_cdma_txrx.grc and see if it works.
Then you can change all other apps accordingly.

I'll be happy to incorporate this in the project should you do it and send me a pull request.
