### ISSUE TITLE
Some questions for gr-cdma

### ISSUE THREAD

**Issue by FairyRYH** [anastas/gr-cdma#38]
Hi Anastas
  I am very interested in your gr-cdma and would like to ask you the following questions:
  1、I want to implement two TX and two RX. Can I change the training sequence to a second TX；
  2、As far as I understand, CDMA is spreading the system to pulse_ data times, if the system symbol rate is 100k and the BW of CDMA is 800k, is that correct；
  3、I saw that you have used a communication frequency of 2.2GHz. I have tried to change the communication frequency to 500kHz, but the data at the receiving end was not output after passing through Stream CRC32, which means that this part was not decoded correctly. Do you know why？
  That's all my questions, thank you very much

**Comment by anastas** [comment]
1. Yes you can
2. I am implementing a CDMA system: you can parameterize the symbol and chip rate. The latter determines the BW.
3. The carrier frequency is completely unrelated to the system implementation: you should use one appropriate for your daughterboards, etc... Clearly you cannot use a 500KHz carrier in a 800KHz BW system!
