### ISSUE TITLE
Make issue in newest commit

### ISSUE THREAD

**Issue by tblake84** [anastas/gr-cdma#5]
I am trying to build the newest commit and make causes the following error:

Scanning dependencies of target gnuradio-cdma
[  4%] Building CXX object lib/CMakeFiles/gnuradio-cdma.dir/packet_header2.cc.o
/opt/cdma/v070615/playback/source/gr-cdma-master/lib/packet_header2.cc: In member function ‘virtual bool gr::cdma::packet_header2::header_formatter(long int, unsigned char*, const std::vector<gr::tag_t>&)’:
/opt/cdma/v070615/playback/source/gr-cdma-master/lib/packet_header2.cc:74:7: error: ‘d_crc_impl’ was not declared in this scope
       d_crc_impl.reset();
       ^
/opt/cdma/v070615/playback/source/gr-cdma-master/lib/packet_header2.cc: In member function ‘virtual bool gr::cdma::packet_header2::header_parser(const unsigned char*, std::vector<gr::tag_t>&)’:
/opt/cdma/v070615/playback/source/gr-cdma-master/lib/packet_header2.cc:140:7: error: ‘d_crc_impl’ was not declared in this scope
       d_crc_impl.reset();
       ^
make[2]: *** [lib/CMakeFiles/gnuradio-cdma.dir/packet_header2.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/gnuradio-cdma.dir/all] Error 2
make: *** [all] Error 2

**Comment by anastas** [comment]
can you be more specific about your gnuradio version/system, etc

**Comment by anastas** [comment]
I cannot recreate your error.
Make works perfectly on my Fedora 20, with the latest gnuradio:

Building for version: v3.7.7.1-204-g55d8f482 / 3.7.8git
