### ISSUE TITLE
cdma_rx.grc is  not stable

### ISSUE THREAD

**Issue by VNDJ** [anastas/gr-cdma#8]
hello anastas
these days,i am using your gr-cdma model with usrp b200,when i run cdma_rx.grc,there are some problems.
the problem is that this model is not stable,sometimes i run this model and it worked well,
but sometimes i run this model ,it dose not work well,the grc crashed,the error message is

gr::log::info:Detected an invalid packet at item (3807)
message debug info
#F

when i shield 

if (!d_header_formatter->header_parser(in, tags)) {
	GR_LOG_INFO(d_logger, boost::format("Detected an invalid packet at item %1%") % nitems_read(0));
     message_port_pub(msg_port_id, pmt::PMT_F);
      } else {
     pmt::pmt_t dict(pmt::make_dict());

then recompile the gr-cdma,there always have the output of error message.
the file i altered is gr-cdma/lib/packet_headerparser_b2_impl.cc
i want to know what the prolem is,why i change the source code of gr-cdma,there still have the error message.
and why the grc is not stable, i think a grc should be boole,work well or not,why this grc just work well sometimes.
thank you

**Comment by anastas** [comment]
I do not understand why you say it is unstable.
When the SNR is low the packet header is not received correctly and this is the error message you are getting.

Please experiment with the application "cdma_txrx" and change the EsN0dB vslue (first slider).
As the values becomes smaller the reception stops with the same message. 
As you increase it it continues. So the porogram has not crashed but it does not find a valid packet header.

**Comment by joseyoel1992** [comment]
Hello Anastas, no way that I serve CDMA scheme for WCDMA technology? I want to send an audio signal from the transmitter and then measure the quality of the audio signal received at the receiver using neural networks.

**Comment by anastas** [comment]
I can try to answer specific questions about this piece of software.
If you have any please post them.
For help on your hw/project, please refer to other venues.

**Comment by joseyoel1992** [comment]
in this project I can transmit audio files with the file sink and file source blocks. I have no usrp.

**Comment by mathursiddarth** [comment]
Hello anastas,
When running the "cdma_txrx", I keep getting the "INFO: Detected an invalid packet at item 0". What does this imply? Is it like you mentioned before that it does not find a valid packet header?
Thank you.
