### ISSUE TITLE
Vector Source - File Source

### ISSUE THREAD

**Issue by joseyoel1992** [anastas/gr-cdma#9]
Hello Anastas,
I am replacing the vector source block by file source block to transmit files on other formats (audio, image, text). But the receiver does not get any type of file. can you help me please.

**Comment by anastas** [comment]
I am not responding to individual questions through github, 
especially if they are unrelated to gr-cdma.
Please post your question on the discuss-gnuradio mailing list.
I will attempt an answer if I see it posted there.
